const {
  HOST,
  PORT,
  DB_CONNECTION_STRING,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  DEFAULT_MOMENT_PRICE,
  STRIPE_SECRET_KEY,
  FACEBOOK_CALLBACK_URL,
  JWT_SECRET,
  JWT_ISSUER,
  JWT_AUDIENCE
} = process.env

export {
  HOST,
  PORT,
  DB_CONNECTION_STRING,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  DEFAULT_MOMENT_PRICE,
  STRIPE_SECRET_KEY,
  FACEBOOK_CALLBACK_URL,
  JWT_SECRET,
  JWT_ISSUER,
  JWT_AUDIENCE
}
