const {
  HOST,
  PORT,
  DB_CONNECTION_STRING,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  JWT_SECRET,
  DEFAULT_MOMENT_PRICE,
  STRIPE_SECRET_KEY
} = process.env

const config = {
  HOST,
  PORT,
  DB_CONNECTION_STRING,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  JWT_SECRET,
  DEFAULT_MOMENT_PRICE,
  STRIPE_SECRET_KEY
}

export default config
